### ISSUE TITLE
delivery todo list

### ISSUE THREAD

**Issue by paulpaul168** [paulpaul168/glint#19]
- [x] sidebar files not click-able if project not selected
- [x] Tried loading project with empty id
- [x] File delete missing *implementation needs testing, I'm 100% there's bugs/it won't work at all*
- [x] help -> 404
- [x] icon (eg. https://tabler-icons.io/)
- [x] Stats Panel Placeholder
- [x] remove pylint urls
- [x] linter mapping update not intuitive (how to update lints without changing file saving them and redoing the lint)
- [x] rust linter add to install script
- [x] only new lint if you send linters to backend
- [x] error if no linter available (show processing?)
- [x] lint error not shown
- [x] permalinks missing (url-parsing)
- [x] links/zips not working
- [x] add file to existing project
- [x] ~~project-wide lint view?~~
- [x] ~~upload folder structure~~ *same as .zip uploading (I will not make a manual folder edit UI)*

**Comment by LuPro** [comment]
if I'm understanding correctly what you mean with project wide lint view: no
